server:
    port: 8080
    contextPath: /jexam
    max-http-header-size: 8192
    compression:
        min-response-size: 512
        enabled: true
        mime-types: text/html,text/css,text/javascript,application/javascript,image/gif,image/png,image/jpg
    tomcat:
      maxThreads: 10
      minSpareThreads: 3
      accesslog:
        pattern: combined
        enabled: true
    undertow:
        io-threads: 4
        worker-threads: 10
        buffer-size: 16384
        accesslog:
            enabled: true
            pattern: combined
logging:
    config: classpath:log4j2.xml
spring:
    freemarker:
      enabled: true
      suffix: .ftl
      charset: UTF-8
      request-context-attribute: request
    thymeleaf:
      enabled: false
      cache: false
      encoding: utf-8
      suffix: .html
      mode: HTML5
    http:
        encoding.charset: UTF-8
        encoding.force: false
        multipart:
          max-file-size: 300MB
          max-request-size: 300MB
          enabled: true
    cache:
        cache-names: ehcache
        ehcache:
            config: ehcache.xml
    datasource:
        role: com.alibaba.druid.pool.DruidDataSource
        name: root
        password: qazwsx123
        url: jdbc:mysql://127.0.0.1:3306/jexam?serverTimezone=UTC&useSSL=false&characterEncoding=utf-8
        driverClassName: com.mysql.cj.jdbc.Driver
        schema: classpath:import.sql
        initialize: false
        sql-script-encoding: UTF-8
        druid:
            max-active: 10
            initial-size: 3
            min-idle: 3
            max-wait: 60000
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            poolPreparedStatements: true
            maxPoolPreparedStatementPerConnectionSize: 20
    jpa:
      show-sql: true
      properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
      hibernate:
        ddl-auto: update
      generate-ddl: true